/**
 * TeacherDashboard — THI-235 Sprint 2.A étape 2.
 *
 * Route `/app/teacher` gated by `<RequireRole allowed={['teacher', 'super_admin']}>`.
 *
 * Scope étape 2 (delivered) :
 *   - List "Mes classes" (the teacher's own, ordered by created_at desc)
 *   - Create class via inline expandable form (name only, institution_id
 *     auto-inherited from profile, invitation_code auto-generated by trigger)
 *   - ClassCard with name + created_at + enrollment count + copy invitation URL
 *
 * Out of scope étape 2 (deferred) :
 *   - Edit class name → v1.1 if requested
 *   - Delete class → v1.1 (requires DELETE RLS check + cascade)
 *   - Listing enrolled students → v1.1, dedicated `/app/teacher/classes/:id`
 *   - Stats per class (lessons completed) → THI-77/78 Phase 9 v2
 *
 * Étape 3 (next) : page `/app/join` consumes `join_class_by_code` RPC for
 * students to enroll. Teacher Dashboard remains unchanged — enrollment
 * count just updates via `useTeacherClasses.refresh()` if the user navigates
 * back and forth.
 *
 * Sidebar entry : added in `Sidebar.tsx` as a flat NavLink "Mes classes",
 * visible only when role ∈ { teacher, super_admin }. If Sprint 2.B adds
 * 2+ more role-gated entries (Mon institution / Statut demande), refactor
 * to a collapsible "Mes outils" section per THI-240.
 */
import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Plus, School } from 'lucide-react';

import { RequireRole } from './auth/RequireRole';
import { ClassCard } from './teacher/ClassCard';
import { CreateClassForm } from './teacher/CreateClassForm';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { useTeacherClasses } from '@/lib/hooks/useTeacherClasses';

export function TeacherDashboard() {
  return (
    <RequireRole allowed={['teacher', 'super_admin']}>
      <TeacherDashboardContent />
    </RequireRole>
  );
}

function TeacherDashboardContent() {
  const { classes, loading, creating, error, createClass } = useTeacherClasses();
  const [isCreating, setIsCreating] = useState(false);

  const handleSubmit = async (name: string) => {
    const created = await createClass(name);
    if (created) {
      setIsCreating(false);
    }
  };

  return (
    <main className="flex-1 px-6 py-8 max-w-6xl mx-auto w-full">
      <Helmet>
        <title>Mes classes — Terminal Learning</title>
        <meta
          name="description"
          content="Gérez vos classes Terminal Learning : créez une classe, récupérez le code d'invitation, partagez l'URL avec vos élèves."
        />
        <meta name="robots" content="noindex,nofollow" />
      </Helmet>

      <header className="mb-6 flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold text-[var(--github-text-primary)] mb-2">
            Mes classes
          </h1>
          <p className="text-sm text-[var(--github-text-secondary)]">
            Crée une classe, partage le code d&apos;invitation avec tes élèves, suis leurs progressions.
          </p>
        </div>
        {!isCreating && (
          <Button
            type="button"
            variant="emerald-soft"
            className="min-h-11 gap-2"
            onClick={() => setIsCreating(true)}
          >
            <Plus size={16} aria-hidden="true" />
            Créer une classe
          </Button>
        )}
      </header>

      <CreateClassForm
        isOpen={isCreating}
        creating={creating}
        error={error}
        onSubmit={handleSubmit}
        onCancel={() => setIsCreating(false)}
      />

      {loading ? (
        <p
          className="text-sm text-[var(--github-text-secondary)] font-mono py-8 text-center"
          aria-busy="true"
        >
          Chargement de tes classes…
        </p>
      ) : classes.length === 0 ? (
        <EmptyState onCreate={() => setIsCreating(true)} disabled={isCreating} />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {classes.map((cls) => (
            <ClassCard key={cls.id} data={cls} />
          ))}
        </div>
      )}
    </main>
  );
}

interface EmptyStateProps {
  onCreate: () => void;
  disabled: boolean;
}

function EmptyState({ onCreate, disabled }: EmptyStateProps) {
  return (
    <Card
      variant="tl-surface"
      className="px-6 py-10 gap-3 text-center items-center"
    >
      <span className="text-emerald-400" aria-hidden="true">
        <School size={32} />
      </span>
      <h2 className="text-base font-medium text-[var(--github-text-primary)]">
        Aucune classe pour le moment
      </h2>
      <p className="text-sm text-[var(--github-text-secondary)] max-w-md">
        Crée ta première classe pour générer un code d&apos;invitation à partager avec tes élèves. Ils pourront rejoindre en un clic via l&apos;URL générée.
      </p>
      {!disabled && (
        <Button
          type="button"
          variant="emerald-soft"
          className="min-h-11 gap-2 mt-2"
          onClick={onCreate}
        >
          <Plus size={16} aria-hidden="true" />
          Créer ma première classe
        </Button>
      )}
    </Card>
  );
}
