/**
 * Regenerates src/test/lessonTheoryGaps.ts from the theory replay (THI-353).
 * Usage: npm run theory:gaps            — only removes fixed gaps / lowers the Windows count
 *        npm run theory:gaps -- --allow-new   — also records NEW gaps (needs a planned fix)
 *
 * The file is a ratchet: without --allow-new this script refuses to add an entry
 * or to raise BASH_SHOWN_ON_WINDOWS_MAX, and prints what it would have added.
 * The header written below is the only source of the generated file's header:
 * update its list of gap families here when a family is fixed.
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { replayTheory, failingKeys, bashOnWindowsLessons } from '../src/test/lessonTheoryReplay';
import { KNOWN_THEORY_GAPS, BASH_SHOWN_ON_WINDOWS_MAX } from '../src/test/lessonTheoryGaps';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'test', 'lessonTheoryGaps.ts');
const allowNew = process.argv.includes('--allow-new');

const rows = replayTheory();
const failing = [...failingKeys(rows)];
const bashLessons = bashOnWindowsLessons(rows).size;

const added = failing.filter((k) => !KNOWN_THEORY_GAPS.has(k));
if (!allowNew && (added.length || bashLessons > BASH_SHOWN_ON_WINDOWS_MAX)) {
  console.error('Refused: the ratchet may only shrink. Fix these, or rerun with --allow-new if a fix is planned:');
  for (const k of added) console.error(`  + ${k}`);
  if (bashLessons > BASH_SHOWN_ON_WINDOWS_MAX) console.error(`  BASH_SHOWN_ON_WINDOWS_MAX ${BASH_SHOWN_ON_WINDOWS_MAX} -> ${bashLessons}`);
  process.exit(1);
}

const byLesson = new Map<string, string[]>();
for (const key of failing) {
  const lesson = key.split(' ')[0];
  byLesson.set(lesson, [...(byLesson.get(lesson) ?? []), key]);
}
let body = '';
for (const [lesson, keys] of byLesson) {
  body += `  // ${lesson}\n`;
  for (const key of keys) body += `  ${JSON.stringify(key)},\n`;
}

writeFileSync(OUT, `/**
 * Known gaps between what a lesson shows and what the terminal prints (THI-353).
 * Generated by scripts/generate-theory-gaps.ts (\`npm run theory:gaps\`) from the
 * replay in lessonTheoryReplay.ts; the list may only shrink. The whole file is
 * rewritten on each run: edit this header in the script, not here.
 *
 * Remaining causes, by family (each has its own planned fix):
 * - Git history: theory shows commits, branches, merges and conflicts the lesson's
 *   starting state does not contain (richer Git setups).
 * - gh (GitHub CLI), background jobs (\`&\`, \`jobs\`, \`fg\`, \`Start-Job\`), \`code\`,
 *   \`ssh-copy-id\`, \`git check-ignore\`, \`git mergetool\`, \`git remote rename\`: not simulated yet.
 * - PowerShell objects: property selection (\`Select-Object Owner\`), Get-Process columns.
 * - Illustrative output in the lesson (placeholders like "[liste des fichiers]",
 *   abbreviated help, an interactive prompt, a clock time): not meant to match.
 *
 * Key: \`<module>/<lesson> b<block index> [<env>] <command>\`.
 */
export const KNOWN_THEORY_GAPS = new Set<string>([
${body}]);

/** Lessons whose code blocks show bash to a Windows learner (no Windows variant). */
export const BASH_SHOWN_ON_WINDOWS_MAX = ${bashLessons};
`);

const removed = [...KNOWN_THEORY_GAPS].filter((k) => !failing.includes(k)).length;
console.log(`gaps ${KNOWN_THEORY_GAPS.size} -> ${failing.length} (removed ${removed}, added ${added.length}); bash shown on Windows ${BASH_SHOWN_ON_WINDOWS_MAX} -> ${bashLessons}`);
