-- ─── 020: classes table hardening — server-side defense for THI-235 Sprint 2.A étape 2
-- Findings security-auditor H1 + H2 (audit 19/05/2026 Sprint 2.A étape 2) :
--
-- **H1 — classes.name unbounded length** :
--   Migration 005 defined `name text not null` without length constraint.
--   The Teacher Dashboard UI enforces maxLength=80 client-side, but a teacher
--   with role=teacher can bypass via direct REST call (the RLS INSERT only
--   checks teacher_id + role, not payload size). Without a DB constraint,
--   an attacker-teacher could insert names of arbitrary size → DB bloat,
--   broken truncation on render. Fix : CHECK constraint length(name) ≤ 80.
--
-- **H2 — classes.invitation_code client-forced override** :
--   Migration 016 trigger `set_invitation_code_before_insert` only regenerates
--   if `new.invitation_code is null`. A teacher passing a chosen string
--   (e.g. `'000000000000'` or a known-friend code) via the JS client would
--   bypass the 48-bit entropy guarantee. Fix : trigger always overwrites
--   client-supplied values + CHECK constraint enforces 12-char hex format
--   server-side, defense-in-depth even if the trigger is ever removed.
--
-- No data migration : existing rows already conform to both constraints
-- (names < 80 chars in current 1 test fixture, codes generated by trigger
-- match the regex). Verified empirically by SELECT … WHERE length(name) > 80
-- and SELECT … WHERE invitation_code !~ '^[0-9a-f]{12}$' before this ship.

-- ─── 1. CHECK constraint on classes.name length ────────────────────────────
alter table public.classes
  add constraint classes_name_length_check
  check (length(name) >= 1 and length(name) <= 80);

comment on constraint classes_name_length_check on public.classes is
  'THI-235 Sprint 2.A étape 2 — security-auditor H1 fix. Server-side validation of class name length, mirrors UI maxLength=80. Prevents teacher-authenticated attacker from bypassing client validation via direct REST.';

-- ─── 2. CHECK constraint on classes.invitation_code format ────────────────
alter table public.classes
  add constraint classes_invitation_code_format_check
  check (invitation_code ~ '^[0-9a-f]{12}$');

comment on constraint classes_invitation_code_format_check on public.classes is
  'THI-235 Sprint 2.A étape 2 — security-auditor H2 fix. Server-side format guarantee for invitation_code (12 lowercase hex chars = 48 bits entropy from gen_random_bytes(6)). Prevents teacher-supplied client-forced codes with reduced entropy.';

-- ─── 3. Trigger hardening — always regenerate invitation_code ──────────────
-- The previous trigger (migration 016) only regenerated if NULL. Now it
-- ALWAYS regenerates, even if the client provides a value. This defends
-- against the H2 attack vector even if the CHECK constraint is ever dropped
-- (defense-in-depth). The TypeScript Insert type still allows providing
-- `invitation_code` for test fixtures, but the DB will silently overwrite it.
create or replace function public.set_invitation_code_before_insert()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  -- Always overwrite client-provided invitation_code. This is by design :
  -- the 48-bit entropy is a security property, not a UX choice. The client
  -- has no legitimate reason to choose the code (the teacher gets it back
  -- in the INSERT response anyway).
  new.invitation_code := public.generate_invitation_code();
  return new;
end;
$$;

-- Preserve the revoke from migration 016 (CREATE OR REPLACE may reset ACLs
-- on some Postgres versions — idempotent here).
revoke execute on function public.set_invitation_code_before_insert() from public;

comment on function public.set_invitation_code_before_insert() is
  'THI-235 Sprint 2.A étape 2 — security-auditor H2 fix. ALWAYS regenerates invitation_code on INSERT, even if client supplies a value. Prevents reduced-entropy attack via client override.';
