-- ─── 021: Fix generate_invitation_code() — qualify extensions.gen_random_bytes
-- THI-235 Sprint 2.A étape 2 — discovered empirically via INSERT test 19/05/2026
--
-- **CRITICAL BUG** : the `generate_invitation_code()` trigger function raises
-- `42883 function gen_random_bytes(integer) does not exist` on every INSERT
-- attempt by a teacher. The previous fix (migration 020 trigger hardening)
-- was correct but does not address the underlying schema-resolution problem.
--
-- Root cause : Supabase places `pgcrypto` in the `extensions` schema, not in
-- `public`. Migration 017 added `SET search_path = public` to
-- `generate_invitation_code()` to satisfy the
-- `function_search_path_mutable` advisor warning. After that change, the
-- bare reference `gen_random_bytes(6)` inside the function body could no
-- longer be resolved (the search_path no longer includes `extensions`).
--
-- The existing class row in `public.classes` was inserted BEFORE migration
-- 017 was applied, so it bears a valid invitation_code generated by a
-- search_path that still included extensions. That hid the regression
-- until the empirical INSERT test today.
--
-- Why this matters now : Sprint 2.A étape 2 introduces a Teacher Dashboard
-- that creates classes via the standard Supabase JS client. Without this
-- fix, the *first* class a teacher tries to create raises 42883 and the
-- whole Sprint 2.A étape 2 UX is broken in prod.
--
-- **Fix** : qualify the call as `extensions.gen_random_bytes(6)` so the
-- function resolves correctly even with the strict `search_path = public`.
-- This preserves the advisor-compliant immutable search_path AND restores
-- the trigger functionality.
--
-- No data migration : the function is replaced via CREATE OR REPLACE.
-- The trigger still references `set_invitation_code_before_insert()`
-- which calls `generate_invitation_code()` (no change there).

create or replace function public.generate_invitation_code()
returns text
language plpgsql
security invoker
set search_path = public
as $$
declare
  candidate text;
  attempts  int := 0;
begin
  loop
    -- Qualify with `extensions.` so the function works even with
    -- search_path = public (set in migration 017 for advisor compliance).
    -- pgcrypto v1.3 is installed in the `extensions` schema by default
    -- on all Supabase projects (verified empirically 19/05/2026).
    candidate := encode(extensions.gen_random_bytes(6), 'hex');
    if not exists (select 1 from public.classes where invitation_code = candidate) then
      return candidate;
    end if;
    attempts := attempts + 1;
    if attempts >= 10 then
      raise exception 'Failed to generate unique invitation code after 10 attempts (extremely unlikely)';
    end if;
  end loop;
end;
$$;

-- Preserve the revoke from migration 016 (CREATE OR REPLACE may reset ACLs
-- on some Postgres versions — idempotent here).
revoke execute on function public.generate_invitation_code() from public;

comment on function public.generate_invitation_code() is
  'THI-235 Sprint 2.A étape 2 — generates 12-char hex invitation_code (48 bits entropy via extensions.gen_random_bytes(6)). Schema-qualified to work under search_path=public (migration 017 advisor compliance). Retries up to 10 times on collision (birthday paradox threshold ~17M classes).';
